# -*- coding: utf-8 -*-
"""Main_GVFNet_Bangladeshi_Braille.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11XUM9eeFsgi5xvHSJ2CMr5TFQXA-gMAi

# GCN + EfficientNet Fusion + Braille Representation
## Thesis: Intelligent Sign Language Recognition and Braille Representation

### Complete Pipeline
```
Raw Image + Hand Coordinates
        ↓
Improved GCN (3-layer residual) + EfficientNet-B0 + ViT
        ↓
Cross-Modal Attention Fusion
        ↓
Predicted BdSL Class (0-46)
        ↓
Bangla Sign Name
        ↓
Braille Unicode + Dot Pattern
```

### GCN Improvements
| Fix | Before | After |
|---|---|---|
| Normalisation | `BatchNorm1d(21)` wrong axis | `LayerNorm(out_features)` correct |
| Depth | 2 layers | 3 layers + residual connections |

### Cell Order
- **Cells 1-8**: Setup — run once per session
- **Cell 9A**: GCN_Only + Visual_Only ablation
- **Cell 9B**: Full Fusion — self-contained, run independently after disconnect
- **Cell 10**: Braille lookup table + visualiser — standalone
- **Cell 11**: Full pipeline demo — requires trained fusion_model from Cell 9B
"""

# ============================================================
# CELL 1: Setup — Mount Drive, Extract Dataset, Install Deps
# ============================================================
from google.colab import drive
drive.mount('/content/drive')

import os
if not os.path.exists('/content/local_data'):
    !cp "/content/drive/MyDrive/3D-Data/BdSL47 A Complete Depth-based Bangla Sign Alphabet and Digit Dataset.zip" /content/dataset.zip
    !unzip -q /content/dataset.zip -d /content/local_data
    print('Extraction Complete!')
else:
    print('Dataset already extracted — skipping.')

!pip install thop tqdm -q

# ============================================================
# CELL 2: Imports
# ============================================================
import os
import re
import copy
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from matplotlib.gridspec import GridSpec
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

import torch
import torch.nn as nn
import torch.optim as optim
from pathlib import Path
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms, models
from PIL import Image
from tqdm import tqdm

from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report, confusion_matrix

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f'Using device: {device}')

# ============================================================
# CELL 3: Hand Adjacency Matrix
# Kipf & Welling (2017) symmetric normalisation: D^{-1/2} A D^{-1/2}
# ============================================================
def get_hand_adjacency_matrix():
    A = np.zeros((21, 21), dtype=np.float32)
    edges = [
        (0,1),(1,2),(2,3),(3,4),
        (0,5),(5,6),(6,7),(7,8),
        (0,9),(9,10),(10,11),(11,12),
        (0,13),(13,14),(14,15),(15,16),
        (0,17),(17,18),(18,19),(19,20)
    ]
    for i, j in edges:
        A[i, j] = 1.0
        A[j, i] = 1.0
    A = A + np.eye(21)
    D = np.diag(np.sum(A, axis=1))
    D_inv_sqrt = np.linalg.inv(np.sqrt(D))
    A_norm = D_inv_sqrt @ A @ D_inv_sqrt
    return torch.tensor(A_norm, dtype=torch.float32)

A_norm = get_hand_adjacency_matrix()
print(f'Adjacency matrix: {A_norm.shape}')

# ============================================================
# CELL 4: Data Collection
# Digit labels shifted +37 to avoid overlap with alphabet labels (0-36).
# ============================================================
def collect_multimodal_data(root_dir, target_users):
    root_path = Path(root_dir)
    samples = []
    all_csvs = [p for p in root_path.rglob('*') if p.suffix.lower() == '.csv']
    print(f'Scanning users {target_users} | {len(all_csvs)} CSVs found...')
    for csv_path in all_csvs:
        path_str = str(csv_path).lower()
        is_target = any(
            f'user {uid}' in path_str or f'user_{uid}' in path_str or
            f'user{uid:02d}' in path_str or f'user {uid:02d}' in path_str
            for uid in target_users
        )
        if not is_target:
            continue
        sign_dir  = csv_path.parent
        img_dirs  = [d for d in sign_dir.iterdir()
                     if d.is_dir() and ('image' in d.name.lower() or 'sign' in d.name.lower())]
        if not img_dirs:
            continue
        img_dir = img_dirs[0]
        available = {}
        for f in img_dir.glob('*'):
            if f.suffix.lower() in ['.jpg','.jpeg','.png','.webp']:
                m = re.search(r'\((\d+)\)', f.name) or re.search(r'(\d+)', f.name)
                if m:
                    available[m.group(1)] = f
        try:
            df = pd.read_csv(csv_path)
            for _, row in df.iterrows():
                raw   = str(row.iloc[0]).strip()
                fname = raw.replace('\\\\','/').replace('//','/')\
                           .replace('\\','/').split('/')[-1]
                img_path = img_dir / fname
                if not img_path.exists():
                    m2 = re.search(r'\((\d+)\)', fname) or re.search(r'(\d+)', fname)
                    if m2 and m2.group(1) in available:
                        img_path = available[m2.group(1)]
                if img_path and img_path.exists():
                    coords = row.iloc[1:64].values.astype(np.float32).reshape(21,3)
                    label  = str(row.iloc[-1]).strip()
                    if 'sign digits' in path_str:
                        label = str(int(float(label)) + 37)
                    samples.append({'img_path': str(img_path),
                                    'coords': coords, 'label': label})
        except Exception as e:
            print(f'  Warning: {csv_path.name} — {e}')
    print(f'  -> {len(samples)} samples')
    return samples

# ============================================================
# CELL 5: Dataset Class + Transforms
# Train: augmented | Val/Test: deterministic
# ============================================================
class BdSLMultimodalDataset(Dataset):
    def __init__(self, samples, transform=None, encoder=None):
        self.samples   = samples
        self.transform = transform
        self.encoder   = encoder

    def __len__(self): return len(self.samples)

    def __getitem__(self, idx):
        s      = self.samples[idx]
        image  = Image.open(s['img_path']).convert('RGB')
        if self.transform:
            image = self.transform(image)
        coords = torch.tensor(s['coords'], dtype=torch.float32)
        if self.encoder:
            label_idx = self.encoder.transform([s['label']])[0]
            return image, coords, torch.tensor(label_idx, dtype=torch.long)
        return image, coords, s['label']


train_transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.RandomHorizontalFlip(p=0.3),
    transforms.ColorJitter(brightness=0.3, contrast=0.3, saturation=0.2),
    transforms.RandomRotation(degrees=15),
    transforms.ToTensor(),
    transforms.Normalize([0.485,0.456,0.406],[0.229,0.224,0.225])
])

eval_transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize([0.485,0.456,0.406],[0.229,0.224,0.225])
])

print('Dataset class and transforms defined.')

# ============================================================
# CELL 6: Architecture
#
# A) ViTAttentionBlock   — global self-attention on EfficientNet tokens
# B) ImprovedGeometricStream (GCN)
#      FIX 1: LayerNorm(out_features) replaces BatchNorm1d(21)
#             Normalises learned feature channels per landmark node.
#      FIX 2: 3 layers + residual connections
#             Layer 1: 3->64   no residual
#             Layer 2: 64->128 projection residual
#             Layer 3: 128->128 identity residual
# C) CrossModalAttentionFusion
#      GCN embedding = Query
#      Visual tokens = Key / Value
# ============================================================

# -----------------------------------------------------------
# A) ViTAttentionBlock
# -----------------------------------------------------------
class ViTAttentionBlock(nn.Module):
    def __init__(self, dim, num_heads, mlp_ratio=4, dropout=0.1):
        super().__init__()
        self.norm1 = nn.LayerNorm(dim)
        self.attn  = nn.MultiheadAttention(
            embed_dim=dim, num_heads=num_heads,
            dropout=dropout, batch_first=True
        )
        self.norm2 = nn.LayerNorm(dim)
        self.mlp   = nn.Sequential(
            nn.Linear(dim, mlp_ratio * dim), nn.GELU(),
            nn.Dropout(dropout),
            nn.Linear(mlp_ratio * dim, dim), nn.Dropout(dropout)
        )

    def forward(self, x):
        normed = self.norm1(x)
        attn_out, _ = self.attn(normed, normed, normed)
        x = x + attn_out
        x = x + self.mlp(self.norm2(x))
        return x


# -----------------------------------------------------------
# Visual Stream: EfficientNet-B0 + ViTAttentionBlock
# -----------------------------------------------------------
class VisualStream(nn.Module):
    def __init__(self, out_dim=256):
        super().__init__()
        efficientnet  = models.efficientnet_b0(weights='DEFAULT')
        self.backbone = efficientnet.features
        self.adapter  = nn.Conv2d(1280, out_dim, kernel_size=1)
        self.transformer = ViTAttentionBlock(dim=out_dim, num_heads=8, dropout=0.1)
        self.pool     = nn.AdaptiveAvgPool2d(1)
        self.proj     = nn.Linear(out_dim, out_dim)

    def forward(self, x):
        x = self.backbone(x)                            # (B,1280,7,7)
        x = self.adapter(x)                             # (B,256,7,7)
        B, C, H, W = x.shape
        tokens = x.view(B, C, H*W).permute(0, 2, 1)   # (B,49,256)
        tokens = self.transformer(tokens)
        visual_tokens = tokens
        visual_embed  = self.pool(
            tokens.permute(0,2,1).view(B, C, H, W)
        ).flatten(1)
        visual_embed  = self.proj(visual_embed)         # (B,256)
        return visual_tokens, visual_embed


# -----------------------------------------------------------
# B) Improved GCN
# -----------------------------------------------------------
class GraphConvLayer(nn.Module):
    """
    FIX 1: LayerNorm(out_features) — correct normalisation axis.
    Normalises learned feature channels per landmark independently.
    """
    def __init__(self, in_features, out_features):
        super().__init__()
        self.linear = nn.Linear(in_features, out_features, bias=False)
        self.norm   = nn.LayerNorm(out_features)
        self.bias   = nn.Parameter(torch.zeros(out_features))

    def forward(self, x, adj):
        support = self.linear(x)
        out     = torch.matmul(adj, support) + self.bias
        return self.norm(out)


class ImprovedGeometricStream(nn.Module):
    """
    FIX 2: 3-layer GCN with residual connections.
    Layer 1: 3->64   (no residual — input dim too small)
    Layer 2: 64->128 (projection residual: 64->128)
    Layer 3: 128->128 (identity residual)
    """
    def __init__(self, adj_matrix, out_dim=256):
        super().__init__()
        self.register_buffer('adj', adj_matrix)
        self.gcn1 = GraphConvLayer(3,   64)
        self.gcn2 = GraphConvLayer(64,  128)
        self.gcn3 = GraphConvLayer(128, 128)
        self.act1 = nn.LeakyReLU(0.2)
        self.act2 = nn.LeakyReLU(0.2)
        self.act3 = nn.LeakyReLU(0.2)
        self.res_proj_1to2 = nn.Linear(64, 128, bias=False)
        self.fc = nn.Sequential(
            nn.Linear(21 * 128, 512),
            nn.LeakyReLU(0.2),
            nn.Dropout(0.3),
            nn.Linear(512, out_dim)
        )

    def forward(self, x):
        x1 = self.act1(self.gcn1(x,  self.adj))
        x2 = self.act2(self.gcn2(x1, self.adj) + self.res_proj_1to2(x1))
        x3 = self.act3(self.gcn3(x2, self.adj) + x2)
        x3 = x3.view(x3.size(0), -1)
        return self.fc(x3)


# -----------------------------------------------------------
# C) Cross-Modal Attention Fusion
# GCN embedding = Query | Visual tokens = Key / Value
# -----------------------------------------------------------
class CrossModalAttentionFusion(nn.Module):
    def __init__(self, dim=256, num_heads=8, dropout=0.1):
        super().__init__()
        self.norm_q     = nn.LayerNorm(dim)
        self.norm_kv    = nn.LayerNorm(dim)
        self.cross_attn = nn.MultiheadAttention(
            embed_dim=dim, num_heads=num_heads,
            dropout=dropout, batch_first=True
        )
        self.norm_out = nn.LayerNorm(dim)
        self.ffn = nn.Sequential(
            nn.Linear(dim, dim*2), nn.GELU(),
            nn.Dropout(dropout),
            nn.Linear(dim*2, dim)
        )

    def forward(self, geo_embed, visual_tokens):
        q  = self.norm_q(geo_embed.unsqueeze(1))
        kv = self.norm_kv(visual_tokens)
        attended, _ = self.cross_attn(q, kv, kv)
        attended = attended.squeeze(1)
        attended = attended + self.ffn(self.norm_out(attended))
        return torch.cat([geo_embed, attended], dim=1)


# -----------------------------------------------------------
# Full Model + Ablation Models
# -----------------------------------------------------------
class MultimodalFusionModel(nn.Module):
    def __init__(self, adj_matrix, num_classes=47):
        super().__init__()
        self.visual_stream    = VisualStream(out_dim=256)
        self.geometric_stream = ImprovedGeometricStream(adj_matrix, out_dim=256)
        self.fusion           = CrossModalAttentionFusion(dim=256, num_heads=8)
        self.classifier       = nn.Sequential(
            nn.Linear(512, 256), nn.GELU(), nn.Dropout(0.3),
            nn.Linear(256, 128), nn.GELU(), nn.Dropout(0.2),
            nn.Linear(128, num_classes)
        )

    def forward(self, img, coords):
        visual_tokens, _ = self.visual_stream(img)
        geo_embed        = self.geometric_stream(coords)
        fused            = self.fusion(geo_embed, visual_tokens)
        return self.classifier(fused)


class GCNOnlyModel(nn.Module):
    def __init__(self, adj_matrix, num_classes=47):
        super().__init__()
        self.geometric_stream = ImprovedGeometricStream(adj_matrix, out_dim=256)
        self.classifier = nn.Sequential(
            nn.Linear(256, 128), nn.GELU(), nn.Dropout(0.3),
            nn.Linear(128, num_classes)
        )
    def forward(self, img, coords):
        return self.classifier(self.geometric_stream(coords))


class VisualOnlyModel(nn.Module):
    def __init__(self, num_classes=47):
        super().__init__()
        self.visual_stream = VisualStream(out_dim=256)
        self.classifier    = nn.Sequential(
            nn.Linear(256, 128), nn.GELU(), nn.Dropout(0.3),
            nn.Linear(128, num_classes)
        )
    def forward(self, img, coords):
        _, visual_embed = self.visual_stream(img)
        return self.classifier(visual_embed)


print('All model classes defined.')
print('  GCN: 3 layers, residual, LayerNorm — Visual: EfficientNet-B0 + ViT')

# ============================================================
# CELL 7: Training & Evaluation Utilities
# ============================================================

def get_optimizer(model):
    backbone_params, other_params = [], []
    for name, param in model.named_parameters():
        if 'visual_stream.backbone' in name:
            backbone_params.append(param)
        else:
            other_params.append(param)
    return optim.AdamW([
        {'params': backbone_params, 'lr': 1e-5},
        {'params': other_params,    'lr': 1e-4}
    ], weight_decay=0.01)


def train_one_epoch(model, loader, optimizer, criterion, scaler):
    model.train()
    correct, total, running_loss = 0, 0, 0.0
    loop = tqdm(loader, leave=False)
    for imgs, coords, labels in loop:
        imgs, coords, labels = imgs.to(device), coords.to(device), labels.to(device)
        optimizer.zero_grad()
        with torch.amp.autocast('cuda'):
            outputs = model(imgs, coords)
            loss    = criterion(outputs, labels)
        scaler.scale(loss).backward()
        scaler.step(optimizer)
        scaler.update()
        _, predicted = outputs.max(1)
        total        += labels.size(0)
        correct      += predicted.eq(labels).sum().item()
        running_loss += loss.item()
        loop.set_postfix(acc=f'{100.*correct/total:.1f}%', loss=f'{loss.item():.3f}')
    return 100.*correct/total, running_loss/len(loader)


@torch.no_grad()
def evaluate(model, loader):
    model.eval()
    correct, total = 0, 0
    all_preds, all_labels = [], []
    for imgs, coords, labels in loader:
        imgs, coords, labels = imgs.to(device), coords.to(device), labels.to(device)
        with torch.amp.autocast('cuda'):
            outputs = model(imgs, coords)
        _, predicted = outputs.max(1)
        total   += labels.size(0)
        correct += predicted.eq(labels).sum().item()
        all_preds.extend(predicted.cpu().numpy())
        all_labels.extend(labels.cpu().numpy())
    return 100.*correct/total, all_preds, all_labels


def train_model(model, train_loader, val_loader, model_name='model',
                epochs=20, patience=7):
    optimizer = get_optimizer(model)
    scheduler = optim.lr_scheduler.CosineAnnealingLR(
        optimizer, T_max=epochs, eta_min=1e-6
    )
    criterion = nn.CrossEntropyLoss(label_smoothing=0.05)
    scaler    = torch.amp.GradScaler('cuda')
    history   = {'train_acc':[], 'val_acc':[], 'train_loss':[]}
    best_val, best_state, pat = 0.0, None, 0

    print(f"\n{'='*60}")
    print(f'Training: {model_name} | {epochs} epochs | patience={patience}')
    print(f"{'='*60}")

    for epoch in range(epochs):
        tr_acc, tr_loss = train_one_epoch(model, train_loader, optimizer, criterion, scaler)
        vl_acc, _, _    = evaluate(model, val_loader)
        scheduler.step()
        history['train_acc'].append(tr_acc)
        history['val_acc'].append(vl_acc)
        history['train_loss'].append(tr_loss)
        lr = scheduler.get_last_lr()[0]
        print(f'Epoch {epoch+1:2d}/{epochs} | Train: {tr_acc:.2f}% '
              f'(loss={tr_loss:.3f}) | Val: {vl_acc:.2f}% | LR: {lr:.2e}')
        if vl_acc > best_val:
            best_val  = vl_acc
            best_state = copy.deepcopy(model.state_dict())
            torch.save(best_state, f'best_{model_name}.pth')
            print(f'  -> New best val: {best_val:.2f}% — saved.')
            pat = 0
        else:
            pat += 1
            if pat >= patience:
                print(f'  Early stopping at epoch {epoch+1}')
                break
    model.load_state_dict(best_state)
    return history, best_val


print('Training utilities defined.')

# ============================================================
# CELL 8: Plotting Utilities
# ============================================================

def plot_training_history(histories, model_names, save_path='training_curves.png'):
    fig, axes = plt.subplots(1, 2, figsize=(16, 6))
    colors = ['#2196F3', '#F44336', '#4CAF50']
    for i, (history, name) in enumerate(zip(histories, model_names)):
        c  = colors[i % len(colors)]
        ep = range(1, len(history['train_acc']) + 1)
        axes[0].plot(ep, history['train_acc'], '--', color=c, alpha=0.6, label=f'{name} (train)')
        axes[0].plot(ep, history['val_acc'],   '-',  color=c, linewidth=2, label=f'{name} (val)')
        axes[1].plot(ep, history['train_loss'], '-', color=c, linewidth=2, label=name)
    axes[0].set_title('Training vs Validation Accuracy', fontsize=14, fontweight='bold')
    axes[0].set_xlabel('Epoch'); axes[0].set_ylabel('Accuracy (%)')
    axes[0].legend(); axes[0].grid(alpha=0.3)
    axes[1].set_title('Training Loss', fontsize=14, fontweight='bold')
    axes[1].set_xlabel('Epoch'); axes[1].set_ylabel('Loss')
    axes[1].legend(); axes[1].grid(alpha=0.3)
    plt.tight_layout()
    plt.savefig(save_path, dpi=150, bbox_inches='tight')
    plt.show()
    print(f'Curves saved: {save_path}')


def plot_confusion_matrix(y_true, y_pred, class_names, save_path='confusion_matrix.png'):
    cm      = confusion_matrix(y_true, y_pred)
    cm_norm = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]
    fig, ax = plt.subplots(figsize=(20, 18))
    sns.heatmap(cm_norm, annot=False, cmap='Blues',
                xticklabels=class_names, yticklabels=class_names, ax=ax)
    ax.set_title('Normalized Confusion Matrix — Full Fusion Model',
                 fontsize=16, fontweight='bold')
    ax.set_xlabel('Predicted'); ax.set_ylabel('True')
    plt.tight_layout()
    plt.savefig(save_path, dpi=150, bbox_inches='tight')
    plt.show()
    print(f'Confusion matrix saved: {save_path}')


def print_ablation_table(results):
    print('\n' + '='*70)
    print(' ABLATION STUDY — Test Set Results')
    print('='*70)
    print(f"{'Model':<35} {'Acc':>8} {'Macro F1':>10} {'Val Acc':>10}")
    print('-'*70)
    for r in results:
        print(f"{r['name']:<35} {r['test_acc']:>7.2f}% {r['macro_f1']:>9.4f}  {r['best_val']:>9.2f}%")
    print('='*70)


print('Plotting utilities defined.')

# ============================================================
# CELL 9A: Ablation — GCN_Only and Visual_Only
#
# Run before Cell 9B if you want overlaid training curves.
# Cell 9B is FULLY SELF-CONTAINED — does NOT need this cell
# after a disconnect.
# ============================================================
from sklearn.metrics import f1_score

SEARCH_ROOT = '/content/local_data/BdSL47 A Complete Depth-based Bangla Sign Alphabet and Digit Dataset'
EPOCHS      = 20
PATIENCE    = 7
BATCH_SIZE  = 32

print('--- Data Collection (Train: Users 1-7 | Val: User 8 | Test: Users 9-10) ---')
train_samples = collect_multimodal_data(SEARCH_ROOT, [1,2,3,4,5,6,7])
val_samples   = collect_multimodal_data(SEARCH_ROOT, [8])
test_samples  = collect_multimodal_data(SEARCH_ROOT, [9,10])

all_labels  = [s['label'] for s in train_samples + val_samples + test_samples]
encoder     = LabelEncoder()
encoder.fit(all_labels)
num_classes = len(encoder.classes_)
print(f'Classes: {num_classes} | Train: {len(train_samples)} | '
      f'Val: {len(val_samples)} | Test: {len(test_samples)}')

train_ds = BdSLMultimodalDataset(train_samples, transform=train_transform, encoder=encoder)
val_ds   = BdSLMultimodalDataset(val_samples,   transform=eval_transform,  encoder=encoder)
test_ds  = BdSLMultimodalDataset(test_samples,  transform=eval_transform,  encoder=encoder)
train_loader = DataLoader(train_ds, batch_size=BATCH_SIZE, shuffle=True,  num_workers=2, pin_memory=True)
val_loader   = DataLoader(val_ds,   batch_size=BATCH_SIZE, shuffle=False, num_workers=2, pin_memory=True)
test_loader  = DataLoader(test_ds,  batch_size=BATCH_SIZE, shuffle=False, num_workers=2, pin_memory=True)

all_histories    = []
ablation_results = []

for model_name, model in [('GCN_Only',    GCNOnlyModel(A_norm, num_classes)),
                           ('Visual_Only', VisualOnlyModel(num_classes))]:
    model = model.to(device)
    history, best_val = train_model(model, train_loader, val_loader,
                                    model_name=model_name, epochs=EPOCHS, patience=PATIENCE)
    all_histories.append(history)
    test_acc, y_pred, y_true = evaluate(model, test_loader)
    macro_f1 = f1_score(y_true, y_pred, average='macro')
    ablation_results.append({'name': model_name, 'test_acc': test_acc,
                             'macro_f1': macro_f1, 'best_val': best_val,
                             'y_pred': y_pred, 'y_true': y_true})
    print(f'\n[{model_name}] Test Acc: {test_acc:.2f}% | Macro F1: {macro_f1:.4f}\n')

print_ablation_table(ablation_results)
print('\nDone. Run Cell 9B for Full Fusion.')

# ============================================================
# CELL 9B: Full Fusion — FULLY SELF-CONTAINED
#
# After any disconnect, run ONLY:
#   Cells 1 -> 2 -> 3 -> 4 -> 5 -> 6 -> 7 -> 8 -> THIS CELL
#
# No dependency on Cell 9A whatsoever.
# Produces: training log, test results, per-class report,
#           training curves PNG, confusion matrix PNG.
# fusion_model, encoder, test_samples remain in memory
# for Cell 11 (Braille pipeline demo).
# ============================================================
from sklearn.metrics import f1_score, classification_report, confusion_matrix
import numpy as np

SEARCH_ROOT = '/content/local_data/BdSL47 A Complete Depth-based Bangla Sign Alphabet and Digit Dataset'
EPOCHS      = 20
PATIENCE    = 7
BATCH_SIZE  = 32

print('--- Data Collection ---')
train_samples = collect_multimodal_data(SEARCH_ROOT, [1,2,3,4,5,6,7])
val_samples   = collect_multimodal_data(SEARCH_ROOT, [8])
test_samples  = collect_multimodal_data(SEARCH_ROOT, [9,10])

all_labels  = [s['label'] for s in train_samples + val_samples + test_samples]
encoder     = LabelEncoder()
encoder.fit(all_labels)
num_classes = len(encoder.classes_)
print(f'Classes: {num_classes} | Train: {len(train_samples)} | '
      f'Val: {len(val_samples)} | Test: {len(test_samples)}')

train_ds = BdSLMultimodalDataset(train_samples, transform=train_transform, encoder=encoder)
val_ds   = BdSLMultimodalDataset(val_samples,   transform=eval_transform,  encoder=encoder)
test_ds  = BdSLMultimodalDataset(test_samples,  transform=eval_transform,  encoder=encoder)
train_loader = DataLoader(train_ds, batch_size=BATCH_SIZE, shuffle=True,  num_workers=2, pin_memory=True)
val_loader   = DataLoader(val_ds,   batch_size=BATCH_SIZE, shuffle=False, num_workers=2, pin_memory=True)
test_loader  = DataLoader(test_ds,  batch_size=BATCH_SIZE, shuffle=False, num_workers=2, pin_memory=True)

fusion_model = MultimodalFusionModel(A_norm, num_classes).to(device)
total_params = sum(p.numel() for p in fusion_model.parameters() if p.requires_grad)
print(f'\nFull Fusion | Trainable params: {total_params:,}')

history_fusion, best_val_fusion = train_model(
    fusion_model, train_loader, val_loader,
    model_name='Full_Fusion', epochs=EPOCHS, patience=PATIENCE
)

test_acc_fusion, y_pred_fusion, y_true_fusion = evaluate(fusion_model, test_loader)
macro_f1_fusion = f1_score(y_true_fusion, y_pred_fusion, average='macro')
micro_f1_fusion = f1_score(y_true_fusion, y_pred_fusion, average='micro')

print(f"\n{'='*60}")
print(f'  Improved GCN + EfficientNet Fusion — Final Test Results')
print(f'  Train: Users 1-7 | Val: User 8 | Test: Users 9-10')
print(f"{'='*60}")
print(f'  Test Accuracy : {test_acc_fusion:.2f}%')
print(f'  Macro F1      : {macro_f1_fusion:.4f}')
print(f'  Micro F1      : {micro_f1_fusion:.4f}')
print(f'  Best Val Acc  : {best_val_fusion:.2f}%')
print(f"{'='*60}")

print('\n--- Detailed Classification Report ---')
print(classification_report(y_true_fusion, y_pred_fusion,
                            target_names=[str(c) for c in encoder.classes_]))

# Training curves
fig, axes = plt.subplots(1, 2, figsize=(14, 5))
ep = range(1, len(history_fusion['train_acc']) + 1)
axes[0].plot(ep, history_fusion['train_acc'], '--', color='#2196F3', alpha=0.6, label='Train')
axes[0].plot(ep, history_fusion['val_acc'],   '-',  color='#2196F3', linewidth=2, label='Val')
axes[0].set_title('Full Fusion — Accuracy', fontweight='bold')
axes[0].set_xlabel('Epoch'); axes[0].set_ylabel('Accuracy (%)')
axes[0].legend(); axes[0].grid(alpha=0.3)
axes[1].plot(ep, history_fusion['train_loss'], '-', color='#F44336', linewidth=2)
axes[1].set_title('Full Fusion — Loss', fontweight='bold')
axes[1].set_xlabel('Epoch'); axes[1].set_ylabel('Loss')
axes[1].grid(alpha=0.3)
plt.suptitle('Improved GCN + EfficientNet | User-Independent Evaluation', style='italic')
plt.tight_layout()
plt.savefig('fusion_training_curves.png', dpi=150, bbox_inches='tight')
plt.show()
print('Curves saved: fusion_training_curves.png')

# Confusion matrix
cm      = confusion_matrix(y_true_fusion, y_pred_fusion)
cm_norm = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]
fig2, ax = plt.subplots(figsize=(20, 18))
sns.heatmap(cm_norm, annot=False, cmap='Blues',
            xticklabels=[str(c) for c in encoder.classes_],
            yticklabels=[str(c) for c in encoder.classes_], ax=ax)
ax.set_title('Improved GCN Fusion — Normalized Confusion Matrix\n'
             'User-Independent: Train 1-7 | Val 8 | Test 9-10',
             fontsize=15, fontweight='bold')
ax.set_xlabel('Predicted'); ax.set_ylabel('True')
plt.tight_layout()
plt.savefig('fusion_confusion_matrix.png', dpi=150, bbox_inches='tight')
plt.show()
print('Confusion matrix saved: fusion_confusion_matrix.png')
print('\nAll done. fusion_model, encoder and test_samples are in memory for Cell 11.')

# ============================================================
# CELL 10 — Bangladeshi Braille Representation Module
#
# References:
#   Hossain et al., IGI Global, 2013.
#   DOI: 10.4018/978-1-4666-3970-6.ch002
#   Ahmed et al., Knowledge-Based Systems, vol.330, 2025.
#   DOI: 10.1016/j.knosys.2025.114546
# ============================================================

import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import matplotlib.gridspec as mgridspec
import numpy as np

# ── Palette ──────────────────────────────────────────────────────────────────
C_ALPHA     = '#185FA5'   # navy  — alphabet raised dot
C_ALPHA_E   = '#0C447C'   # darker edge
C_DIGIT     = '#A32D2D'   # deep red — digit raised dot
C_DIGIT_E   = '#791F1F'
C_NS        = '#185FA5'   # number-sign cell = same navy
C_FLAT      = '#E8EDF3'   # unraised
C_FLAT_E    = '#C8D4E0'
C_BORDER    = '#5F7080'
C_BG        = '#FFFFFF'
C_CARD      = '#F7F9FC'
C_TEXT      = '#1A2B3C'
C_MUTED     = '#5A6A7A'
C_ALPHA_TAG = '#E6EEF8'
C_DIGIT_TAG = '#FCEAEA'

NS_MASK = 0b111100   # dots 3,4,5,6  →  U+283C

BDSL47_BRAILLE = {
    0:  {'sign':'অ','name':'A (Aw)',      'mask':0b000001,'type':'alpha'},
    1:  {'sign':'আ','name':'AA',          'mask':0b011100,'type':'alpha'},
    2:  {'sign':'ই','name':'I',           'mask':0b001010,'type':'alpha'},
    3:  {'sign':'উ','name':'U',           'mask':0b100101,'type':'alpha'},
    4:  {'sign':'র','name':'R',           'mask':0b010111,'type':'alpha'},
    5:  {'sign':'এ','name':'E',           'mask':0b010001,'type':'alpha'},
    6:  {'sign':'ঐ','name':'OI',          'mask':0b001100,'type':'alpha'},
    7:  {'sign':'ও','name':'O',           'mask':0b010101,'type':'alpha'},
    8:  {'sign':'ঔ','name':'OU',          'mask':0b101010,'type':'alpha'},
    9:  {'sign':'ক','name':'KA',          'mask':0b000101,'type':'alpha'},
    10: {'sign':'খ','name':'KHA',         'mask':0b101101,'type':'alpha'},
    11: {'sign':'গ','name':'GA',          'mask':0b011011,'type':'alpha'},
    12: {'sign':'ঘ','name':'GHA',         'mask':0b100011,'type':'alpha'},
    13: {'sign':'ঙ','name':'NGA',         'mask':0b101100,'type':'alpha'},
    14: {'sign':'চ','name':'CA',          'mask':0b001001,'type':'alpha'},
    15: {'sign':'ছ','name':'CHA',         'mask':0b100001,'type':'alpha'},
    16: {'sign':'জ','name':'JA',          'mask':0b011010,'type':'alpha'},
    17: {'sign':'ঝ','name':'JHA',         'mask':0b110101,'type':'alpha'},
    18: {'sign':'ঞ','name':'NYA',         'mask':0b010010,'type':'alpha'},
    19: {'sign':'ট','name':'TA (retro)',  'mask':0b111110,'type':'alpha'},
    20: {'sign':'ঠ','name':'THA (retro)', 'mask':0b111010,'type':'alpha'},
    21: {'sign':'ড','name':'DA (retro)',  'mask':0b101011,'type':'alpha'},
    22: {'sign':'ঢ','name':'DDA',         'mask':0b111111,'type':'alpha'},
    23: {'sign':'ণ','name':'NA',          'mask':0b011101,'type':'alpha'},
    24: {'sign':'ত','name':'TA (dental)', 'mask':0b011110,'type':'alpha'},
    25: {'sign':'থ','name':'THA (dental)','mask':0b111001,'type':'alpha'},
    26: {'sign':'দ','name':'DA (dental)', 'mask':0b011001,'type':'alpha'},
    27: {'sign':'ধ','name':'DHA',         'mask':0b101110,'type':'alpha'},
    28: {'sign':'প','name':'PA',          'mask':0b001111,'type':'alpha'},
    29: {'sign':'ফ','name':'PHA',         'mask':0b001011,'type':'alpha'},
    30: {'sign':'ব','name':'BA',          'mask':0b000011,'type':'alpha'},
    31: {'sign':'ম','name':'MA',          'mask':0b001101,'type':'alpha'},
    32: {'sign':'ল','name':'LA',          'mask':0b000111,'type':'alpha'},
    33: {'sign':'শ','name':'SHA',         'mask':0b101001,'type':'alpha'},
    34: {'sign':'হ','name':'HA',          'mask':0b010011,'type':'alpha'},
    35: {'sign':'ড়','name':'RRA',        'mask':0b111011,'type':'alpha'},
    36: {'sign':'ঁ','name':'CHANDRABINDU','mask':0b000100,'type':'alpha'},
    37: {'sign':'০','name':'Digit 0',    'mask':0b011010,'type':'digit'},
    38: {'sign':'১','name':'Digit 1',    'mask':0b000001,'type':'digit'},
    39: {'sign':'২','name':'Digit 2',    'mask':0b000011,'type':'digit'},
    40: {'sign':'৩','name':'Digit 3',    'mask':0b001001,'type':'digit'},
    41: {'sign':'৪','name':'Digit 4',    'mask':0b011001,'type':'digit'},
    42: {'sign':'৫','name':'Digit 5',    'mask':0b010001,'type':'digit'},
    43: {'sign':'৬','name':'Digit 6',    'mask':0b001011,'type':'digit'},
    44: {'sign':'৭','name':'Digit 7',    'mask':0b011011,'type':'digit'},
    45: {'sign':'৮','name':'Digit 8',    'mask':0b010011,'type':'digit'},
    46: {'sign':'৯','name':'Digit 9',    'mask':0b001010,'type':'digit'},
}


# ── Core drawing primitive ────────────────────────────────────────────────────

def _draw_cell(ax, mask, dot_color, dot_edge, x0=0.0, y0=0.0, scale=1.0,
               show_labels=True):
    """
    Draw a standard Braille 2×3 cell inside `ax`.
    x0, y0: bottom-left corner in axes data coords.
    scale:  controls spacing between dots and label placement.

    Dot numbering (Braille standard):
        Col 1   Col 2
    1 ● . 4
    2 ● . 5
    3 ● . 6
    """
    S   = 0.28 * scale   # column spacing
    V   = 0.28 * scale   # row spacing
    R   = 0.095 * scale  # dot radius
    LO  = 0.07 * scale   # label offset from dot centre

    # dot centres: (col_x, row_y) indexed as dots 1-6
    col_xs = [x0 + 0.12*scale, x0 + 0.12*scale + S]
    row_ys = [y0 + 0.60*scale, y0 + 0.32*scale, y0 + 0.04*scale]

    patt = [(mask >> i) & 1 for i in range(6)]
    dot_map = {0:(0,0), 1:(0,1), 2:(0,2), 3:(1,0), 4:(1,1), 5:(1,2)}

    if show_labels:
        # Column headers
        ax.text(col_xs[0], y0 + 0.74*scale, 'Col 1',
                ha='center', va='bottom', fontsize=6, color=C_MUTED)
        ax.text(col_xs[1], y0 + 0.74*scale, 'Col 2',
                ha='center', va='bottom', fontsize=6, color=C_MUTED)
        # Row numbers
        for ri, (lbl_l, lbl_r) in enumerate(zip(['1','2','3'],['4','5','6'])):
            ax.text(col_xs[0] - LO - R - 0.03*scale, row_ys[ri],
                    lbl_l, ha='right', va='center', fontsize=6, color=C_MUTED)
            ax.text(col_xs[1] + LO + R + 0.03*scale, row_ys[ri],
                    lbl_r, ha='left',  va='center', fontsize=6, color=C_MUTED)

    for i in range(6):
        ci, ri = dot_map[i]
        fc = dot_color if patt[i] else C_FLAT
        ec = dot_edge  if patt[i] else C_FLAT_E
        ax.add_patch(plt.Circle(
            (col_xs[ci], row_ys[ri]), R,
            facecolor=fc, edgecolor=ec, linewidth=0.6, zorder=3
        ))


def _cell_width(scale=1.0):
    """Total width of one cell (including label clearance on each side)."""
    return 0.60 * scale


def _cell_height(scale=1.0):
    return 0.80 * scale


def _draw_bordered_cell(ax, mask, dot_color, dot_edge, x0, y0, scale=1.0,
                        show_labels=True, bg=C_CARD, border=C_BORDER):
    """Draw cell with a rounded border box."""
    w = _cell_width(scale)
    h = _cell_height(scale)
    ax.add_patch(mpatches.FancyBboxPatch(
        (x0, y0), w, h,
        boxstyle='round,pad=0.015',
        facecolor=bg, edgecolor=border, linewidth=0.8, zorder=1
    ))
    _draw_cell(ax, mask, dot_color, dot_edge, x0, y0, scale, show_labels)


# ── Single-class panel (cell + metadata) ─────────────────────────────────────

def _render_class_panel(fig, spec, cls_idx):
    """
    Render one class into a 2-row subplot pair (cell on top, metadata below).
    spec: a SubplotSpec from gridspec.
    """
    entry    = BDSL47_BRAILLE[cls_idx]
    is_digit = entry['type'] == 'digit'
    dc       = C_DIGIT   if is_digit else C_ALPHA
    de       = C_DIGIT_E if is_digit else C_ALPHA_E
    mask     = entry['mask']
    uc_str   = (f"U+283C · U+{0x2800+mask:04X}" if is_digit
                else f"U+{0x2800+mask:04X}")
    active   = ', '.join(str(i+1) for i in range(6) if (mask>>i)&1) or '—'
    tag      = 'DIGIT' if is_digit else 'ALPHA'
    tag_col  = C_DIGIT if is_digit else C_ALPHA

    inner = mgridspec.GridSpecFromSubplotSpec(
        2, 1, subplot_spec=spec,
        height_ratios=[3, 1.4], hspace=0.06
    )
    ax_c = fig.add_subplot(inner[0])
    ax_m = fig.add_subplot(inner[1])

    # ── Cell panel ────────────────────────────────────────────────────────────
    ax_c.set_aspect('equal'); ax_c.axis('off')
    ax_c.set_facecolor(C_BG)
    S = 1.0

    if is_digit:
        # Two bordered cells: Number Sign | Digit
        ax_c.set_xlim(0, 2.0); ax_c.set_ylim(0, 1.0)
        _draw_bordered_cell(ax_c, NS_MASK, C_NS, C_ALPHA_E, 0.02, 0.08, S*0.92,
                            show_labels=True, bg=C_CARD)
        _draw_bordered_cell(ax_c, mask,    dc,   de,         1.02, 0.08, S*0.92,
                            show_labels=True, bg=C_CARD)
        ax_c.text(0.02 + _cell_width(S*0.92)/2, 0.03,
                  'Num sign', ha='center', va='top', fontsize=5.5, color=C_MUTED)
        ax_c.text(1.02 + _cell_width(S*0.92)/2, 0.03,
                  'Digit',    ha='center', va='top', fontsize=5.5, color=C_MUTED)
    else:
        ax_c.set_xlim(0, 1.0); ax_c.set_ylim(0, 1.0)
        x_off = (1.0 - _cell_width(S)) / 2
        _draw_bordered_cell(ax_c, mask, dc, de, x_off, 0.08, S,
                            show_labels=True, bg=C_CARD)

    # Class + type tag in top-left
    ax_c.text(0.01, 0.99, f'#{cls_idx}', ha='left', va='top',
              fontsize=6.5, color=C_MUTED, fontweight='bold',
              transform=ax_c.transAxes)
    ax_c.text(0.99, 0.99, tag, ha='right', va='top',
              fontsize=5.5, color=tag_col, fontweight='bold',
              transform=ax_c.transAxes)

    # ── Metadata panel ────────────────────────────────────────────────────────
    ax_m.axis('off'); ax_m.set_facecolor(C_BG)
    cell_lbl = '2-cell' if is_digit else '1-cell'
    ax_m.text(0.5, 0.98,
              f"{entry['sign']}  {entry['name']}  [{cell_lbl}]",
              ha='center', va='top', fontsize=7.0, color=C_TEXT,
              fontweight='bold', transform=ax_m.transAxes)
    ax_m.text(0.5, 0.58,
              f"↳ {uc_str}",
              ha='center', va='top', fontsize=6.0, color=C_MUTED,
              fontfamily='monospace', transform=ax_m.transAxes)
    ax_m.text(0.5, 0.20,
              f"Dots: {active}",
              ha='center', va='top', fontsize=6.0, color=C_MUTED,
              transform=ax_m.transAxes)


# ── Public: sample cells figure ──────────────────────────────────────────────

def plot_sample_braille_cells(class_indices=None,
                              save_path='braille_sample_cells.png'):
    """
    A clean single-row reference panel of 8 representative classes.
    """
    if class_indices is None:
        class_indices = [0, 1, 9, 14, 26, 33, 37, 46]

    n       = len(class_indices)
    widths  = [2.6 if BDSL47_BRAILLE[c]['type']=='digit' else 1.6
               for c in class_indices]
    fig_w   = sum(widths) + 0.8
    fig     = plt.figure(figsize=(fig_w, 4.0), facecolor=C_BG)
    fig.patch.set_facecolor(C_BG)

    gs = mgridspec.GridSpec(
        1, n,
        width_ratios=widths,
        wspace=0.30,
        left=0.02, right=0.98,
        top=0.84,  bottom=0.04
    )
    for col, cls in enumerate(class_indices):
        _render_class_panel(fig, gs[0, col], cls)

    # Legend
    legend_els = [
        mpatches.Patch(facecolor=C_ALPHA, edgecolor=C_ALPHA_E,
                       linewidth=0.6, label='Alphabet  —  raised dot'),
        mpatches.Patch(facecolor=C_DIGIT, edgecolor=C_DIGIT_E,
                       linewidth=0.6, label='Digit  —  raised dot'),
        mpatches.Patch(facecolor=C_FLAT,  edgecolor=C_FLAT_E,
                       linewidth=0.6, label='Unraised dot'),
    ]
    fig.legend(handles=legend_els, loc='upper right',
               fontsize=7.5, framealpha=0.95, frameon=True,
               edgecolor=C_FLAT_E, bbox_to_anchor=(0.99, 0.99))

    fig.suptitle(
        'Sample Braille cells — Bangladeshi Braille\n'
        'Filled circle = raised dot  ·  Row/column numbers per cell  ·  '
        'Ref: Hossain et al. 2013 (IGI) + Ahmed et al. 2025 (KBS)',
        fontsize=8.5, color=C_TEXT, y=0.97
    )
    plt.savefig(save_path, dpi=180, bbox_inches='tight', facecolor=C_BG)
    plt.show()
    print(f'Saved: {save_path}')


# ── Public: full 47-class mapping grid ───────────────────────────────────────

def plot_braille_grid(class_indices=None, ncols=8,
                      save_path='braille_full_mapping.png'):
    """
    Full 47-class mapping grid.  Navy = alphabet · Red = digit.
    """
    if class_indices is None:
        class_indices = list(range(47))

    n     = len(class_indices)
    nrows = (n + ncols - 1) // ncols

    # Uniform panel width (digit 2-cell cards are wider but tolerable in grid)
    pw    = 2.05
    fig_w = ncols * pw + 0.4
    fig_h = nrows * 4.0 + 0.9

    fig = plt.figure(figsize=(fig_w, fig_h), facecolor=C_BG)
    fig.patch.set_facecolor(C_BG)

    gs = mgridspec.GridSpec(
        nrows, ncols,
        wspace=0.35, hspace=0.10,
        left=0.01, right=0.99,
        top=0.94,  bottom=0.01
    )
    for idx, cls in enumerate(class_indices):
        r, c = idx // ncols, idx % ncols
        _render_class_panel(fig, gs[r, c], cls)

    for idx in range(len(class_indices), nrows*ncols):
        r, c = idx // ncols, idx % ncols
        ax = fig.add_subplot(gs[r, c]); ax.axis('off')

    legend_els = [
        mpatches.Patch(facecolor=C_ALPHA, edgecolor=C_ALPHA_E,
                       linewidth=0.6, label='Alphabet  (classes 0–36)'),
        mpatches.Patch(facecolor=C_DIGIT, edgecolor=C_DIGIT_E,
                       linewidth=0.6, label='Digit  (classes 37–46)'),
        mpatches.Patch(facecolor=C_FLAT,  edgecolor=C_FLAT_E,
                       linewidth=0.6, label='Unraised dot'),
    ]
    fig.legend(handles=legend_els, loc='upper right',
               fontsize=8, framealpha=0.95, frameon=True,
               edgecolor=C_FLAT_E, bbox_to_anchor=(0.99, 0.995))

    fig.suptitle(
        'BdSL47 — Complete Bangladeshi Braille mapping  (all 47 patterns verified)\n'
        'Classes 0–36: Bangla alphabet  ·  Classes 37–46: Bangla digits  ·  '
        'Filled circle = raised dot  ·  Digit classes: Number Sign + Digit cell\n'
        'Ref: Hossain et al. 2013, IGI Global  +  Ahmed et al. 2025, '
        'Knowledge-Based Systems',
        fontsize=9, color=C_TEXT, y=0.995
    )
    plt.savefig(save_path, dpi=150, bbox_inches='tight', facecolor=C_BG)
    plt.show()
    print(f'Saved: {save_path}')


# ── Utilities ─────────────────────────────────────────────────────────────────

def get_dot_pattern(mask):
    return [(mask >> i) & 1 for i in range(6)]

def class_to_braille(cls):
    e  = BDSL47_BRAILLE[cls]
    uc = chr(0x2800 + e['mask'])
    return (chr(0x2800 + NS_MASK) + uc, e) if e['type']=='digit' else (uc, e)

def sign_sequence_to_braille(seq):
    out, in_run = '', False
    for cls in seq:
        e  = BDSL47_BRAILLE[cls]
        uc = chr(0x2800 + e['mask'])
        if e['type'] == 'digit':
            if not in_run: out += chr(0x2800 + NS_MASK); in_run = True
        else:
            in_run = False
        out += uc
    return out


# ── Print verified lookup table ───────────────────────────────────────────────
print('BdSL47 → Bangladeshi Braille   (Hossain 2013 + Ahmed 2025)')
print('='*72)
print(f"{'Cls':>4}  {'Type':>6}  {'Sign':>8}  {'Name':<20}  {'Unicode':>24}  Dots")
print('-'*72)
for idx in range(47):
    e = BDSL47_BRAILLE[idx]; mask = e['mask']
    dots = get_dot_pattern(mask)
    active = ','.join(str(i+1) for i,d in enumerate(dots) if d) or '—'
    uc_str = (f"U+283C · U+{0x2800+mask:04X}" if e['type']=='digit'
              else f"U+{0x2800+mask:04X}")
    print(f"{idx:>4}  {e['type']:>6}  {e['sign']:>8}  {e['name']:<20}  "
          f"{uc_str:>24}  [{active}]")
print('='*72)

plot_sample_braille_cells()
plot_braille_grid()

# ============================================================
# CELL 11 — End-to-End Pipeline Demo
# Requires: fusion_model, encoder, test_samples  (from Cell 9B)
# ============================================================

import torch
from torchvision import transforms
from PIL import Image as PILImage
from matplotlib.gridspec import GridSpec, GridSpecFromSubplotSpec
import random

# ── Colour reuse from Cell 10 ─────────────────────────────────────────────────
C_CORRECT   = '#1A6B3A'
C_INCORRECT = '#A32D2D'
C_INFO_BG   = '#F0F4F8'
C_ARROW     = '#8096A8'


EVAL_TF = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
])

FINGER_EDGES = {
    'Thumb':  [(0,1),(1,2),(2,3),(3,4)],
    'Index':  [(0,5),(5,6),(6,7),(7,8)],
    'Middle': [(0,9),(9,10),(10,11),(11,12)],
    'Ring':   [(0,13),(13,14),(14,15),(15,16)],
    'Pinky':  [(0,17),(17,18),(18,19),(19,20)],
}
FINGER_COLORS = {
    'Thumb':'#E53935','Index':'#1E88E5','Middle':'#43A047',
    'Ring':'#FB8C00','Pinky':'#8E24AA',
}
TIP_LABELS = {4:'T', 8:'I', 12:'M', 16:'R', 20:'P'}


def _panel_arrow(fig, x, y=0.46):
    """Draw a thin centred arrow between panels."""
    fig.text(x, y, '→', ha='center', va='center',
             fontsize=18, color=C_ARROW,
             transform=fig.transFigure)


def _draw_hand_panel(ax, coords):
    """
    Coloured hand skeleton with fingertip labels, wrist highlight,
    and z-depth annotation. Pixel coords from depth sensor → y-axis flipped.
    """
    cn = coords.numpy() if hasattr(coords, 'numpy') else np.array(coords)
    xs, ys = cn[:, 0], cn[:, 1]
    z_lo, z_hi = cn[:, 2].min(), cn[:, 2].max()

    for finger, edges in FINGER_EDGES.items():
        fc = FINGER_COLORS[finger]
        for s, t in edges:
            ax.plot([xs[s], xs[t]], [ys[s], ys[t]], '-',
                    color=fc, lw=2.0, alpha=0.88, zorder=2)

    ax.scatter(xs, ys, c='#37474F', s=22, zorder=4, linewidths=0)
    ax.scatter(xs[0], ys[0], c='#FFD600', s=55, zorder=5,
               edgecolors='#333333', linewidths=0.8)
    ax.text(xs[0], ys[0], ' 0', ha='left', va='center',
            fontsize=6, color='#333')

    for tip, lbl in TIP_LABELS.items():
        ax.text(xs[tip], ys[tip], f' {lbl}', ha='left', va='center',
                fontsize=6.5, color='#2C3E50', fontweight='bold')

    ax.invert_yaxis()
    ax.set_title(
        f'② Hand keypoints (x, y)  ·  21 landmarks\n'
        f'z-depth range: [{z_lo:.3f}, {z_hi:.3f}]',
        fontsize=8, pad=5, color=C_TEXT
    )
    ax.set_xlabel('x', fontsize=7, color=C_MUTED, labelpad=2)
    ax.set_ylabel('y', fontsize=7, color=C_MUTED, labelpad=2)
    ax.tick_params(labelsize=6, colors='#AAA')
    for sp in ax.spines.values():
        sp.set_edgecolor('#DDDDDD'); sp.set_linewidth(0.5)

    legend_els = ([plt.Line2D([0],[0], color=FINGER_COLORS[f], lw=2, label=f)
                   for f in FINGER_EDGES]
                  + [plt.Line2D([0],[0], marker='o', color='w',
                                markerfacecolor='#FFD600', markersize=7,
                                markeredgecolor='#333', mew=0.7,
                                label='Wrist (0)')])
    ax.legend(handles=legend_els, fontsize=6, loc='lower right',
              framealpha=0.9, handlelength=1.0)


def _draw_output_panel(ax, pred_cls, confidence, true_cls):
    """
    Model output info box: confidence bar, field table.
    """
    ax.set_xlim(0, 1); ax.set_ylim(0, 1); ax.axis('off')
    e        = BDSL47_BRAILLE[pred_cls]
    te       = BDSL47_BRAILLE[true_cls]
    is_digit = e['type'] == 'digit'
    mask     = e['mask']
    active   = ', '.join(str(i+1) for i in range(6) if (mask>>i)&1) or '—'
    uc_str   = (f"U+283C · U+{0x2800+mask:04X}" if is_digit
                else f"U+{0x2800+mask:04X}")
    correct  = pred_cls == true_cls
    rc       = C_CORRECT if correct else C_INCORRECT
    cell_lbl = '2-cell (NS + digit)' if is_digit else '1-cell (letter)'
    type_lbl = 'Digit sign' if is_digit else 'Alphabet sign'
    braille_str, _ = class_to_braille(pred_cls)

    # Header bar
    ax.add_patch(mpatches.FancyBboxPatch(
        (0.02, 0.90), 0.96, 0.085,
        boxstyle='round,pad=0.01',
        facecolor=C_CORRECT, edgecolor='none', zorder=2
    ))
    ax.text(0.50, 0.943, '③  Model output',
            ha='center', va='center', fontsize=9,
            fontweight='bold', color='white', zorder=3,
            transform=ax.transAxes)

    # Confidence bar
    ax.add_patch(mpatches.FancyBboxPatch(
        (0.02, 0.80), 0.96, 0.07,
        boxstyle='round,pad=0.005',
        facecolor='#DDE5EE', edgecolor='none', zorder=1
    ))
    ax.add_patch(mpatches.FancyBboxPatch(
        (0.02, 0.80), 0.96*(confidence/100), 0.07,
        boxstyle='round,pad=0.005',
        facecolor=C_CORRECT, edgecolor='none', zorder=2
    ))
    ax.text(0.50, 0.835, f'Confidence: {confidence:.1f}%',
            ha='center', va='center', fontsize=8,
            fontweight='bold', color='white', zorder=3,
            transform=ax.transAxes)

    # Outer border
    ax.add_patch(mpatches.FancyBboxPatch(
        (0.01, 0.01), 0.98, 0.97,
        boxstyle='round,pad=0.01',
        linewidth=0.8, edgecolor='#C8D4E0',
        facecolor=C_INFO_BG, zorder=0
    ))

    # Field rows
    fields = [
        ('Predicted class', f'{pred_cls}',          C_ALPHA),
        ('Sign name',       e['name'],               C_ALPHA),
        ('Sign symbol',     e['sign'],               C_TEXT),
        ('Type',            type_lbl,                C_TEXT),
        ('Confidence',      f'{confidence:.1f}%',    C_TEXT),
        ('True class',      f'{true_cls} — {te["name"]}', C_TEXT),
        ('Result',          'Correct ✓' if correct else 'Incorrect ✗', rc),
        (None, None, None),
        ('Braille type',    cell_lbl,                C_TEXT),
        ('Braille char',    braille_str,             C_TEXT),
        ('Unicode',         uc_str,                  C_ALPHA),
        ('Active dots',     active,                  C_ALPHA),
        ('Bitmask',         f'{mask:06b}',           C_MUTED),
    ]
    y = 0.77
    for label, val, col in fields:
        if label is None:
            y -= 0.020; continue
        ax.text(0.06, y, label + ':',
                ha='left', va='top', fontsize=7.2, color=C_MUTED,
                transform=ax.transAxes)
        ax.text(0.46, y, str(val),
                ha='left', va='top', fontsize=7.2, color=col,
                fontweight='bold', transform=ax.transAxes)
        y -= 0.059


def _draw_braille_panel(ax, cls_idx):
    """
    Braille output panel — numbered cell, sign name, unicode.
    """
    ax.set_xlim(0, 1); ax.set_ylim(0, 1); ax.axis('off')
    e        = BDSL47_BRAILLE[cls_idx]
    is_digit = e['type'] == 'digit'
    dc       = C_DIGIT if is_digit else C_ALPHA
    de       = C_DIGIT_E if is_digit else C_ALPHA_E
    mask     = e['mask']
    active   = ', '.join(str(i+1) for i in range(6) if (mask>>i)&1) or '—'
    uc_str   = (f"U+283C · U+{0x2800+mask:04X}" if is_digit
                else f"U+{0x2800+mask:04X}")
    braille_str, _ = class_to_braille(cls_idx)
    tag      = 'DIGIT' if is_digit else 'ALPHA'
    tc       = C_DIGIT if is_digit else C_ALPHA

    ax.text(0.5, 0.99, '④  Braille output',
            ha='center', va='top', fontsize=8.5,
            fontweight='bold', color=C_TEXT, transform=ax.transAxes)
    ax.text(0.5, 0.92, 'Bangladeshi Braille  (Hossain 2013)',
            ha='center', va='top', fontsize=6.5,
            color=C_MUTED, transform=ax.transAxes)
    ax.text(0.08, 0.85, f'#{cls_idx}', ha='left', va='top',
            fontsize=7.5, color=C_MUTED, fontweight='bold',
            transform=ax.transAxes)
    ax.text(0.28, 0.85, e['name'], ha='left', va='top',
            fontsize=8.5, color=tc, fontweight='bold',
            transform=ax.transAxes)
    ax.text(0.88, 0.85, tag, ha='right', va='top',
            fontsize=6.5, color=tc, transform=ax.transAxes)

    # Braille cell centred in lower portion
    S    = 0.88
    cw   = _cell_width(S)
    ch   = _cell_height(S)
    x_cell = (1.0 - (cw if not is_digit else cw*2 + 0.08)) / 2

    if is_digit:
        _draw_bordered_cell(ax, NS_MASK, C_NS, C_ALPHA_E,
                            x_cell,        0.12, S, show_labels=True)
        _draw_bordered_cell(ax, mask,     dc,   de,
                            x_cell+cw+0.08, 0.12, S, show_labels=True)
        ax.text(x_cell + cw/2,         0.08,
                'Num sign', ha='center', va='top', fontsize=5.5, color=C_MUTED,
                transform=ax.transAxes)
        ax.text(x_cell + cw + 0.08 + cw/2, 0.08,
                'Digit', ha='center', va='top', fontsize=5.5, color=C_MUTED,
                transform=ax.transAxes)
    else:
        _draw_bordered_cell(ax, mask, dc, de,
                            x_cell, 0.14, S, show_labels=True)

    ax.text(0.5, 0.05,
            f"{e['sign']}  [{e['name']}]   ↳ {uc_str}",
            ha='center', va='top', fontsize=6.5, color=C_TEXT,
            fontfamily='monospace', transform=ax.transAxes)
    ax.text(0.5, -0.01,
            f'Active dots: {active}',
            ha='center', va='top', fontsize=6.5, color=C_MUTED,
            transform=ax.transAxes)


# ── Single-sample pipeline figure ────────────────────────────────────────────

def run_pipeline(model, image_path, coords_tensor, encoder,
                 true_class=None, save_path='pipeline_single_demo.png'):
    """
    Four-panel figure: Input image → Hand keypoints → Model output → Braille cell.
    """
    img_raw  = PILImage.open(image_path).convert('RGB')
    img_t    = EVAL_TF(img_raw).unsqueeze(0).to(device)
    coords_t = coords_tensor.unsqueeze(0).to(device)

    model.eval()
    with torch.no_grad():
        logits   = model(img_t, coords_t)
        probs    = torch.softmax(logits, dim=1)
        pred_enc = logits.argmax(1).item()

    pred_cls   = int(encoder.inverse_transform([pred_enc])[0])
    confidence = probs[0, pred_enc].item() * 100
    if true_class is None:
        true_class = pred_cls

    correct  = pred_cls == true_class
    suptitle = ('Correctly classified' if correct else 'Incorrectly classified')
    sc       = C_CORRECT if correct else C_INCORRECT

    fig = plt.figure(figsize=(19, 5.8), facecolor=C_BG)
    fig.patch.set_facecolor(C_BG)
    gs  = GridSpec(1, 4, figure=fig,
                   width_ratios=[2.1, 2.0, 2.5, 1.9],
                   wspace=0.10,
                   left=0.03, right=0.97,
                   top=0.83,  bottom=0.09)

    # ── Panel 1: image ────────────────────────────────────────────────────────
    ax_img = fig.add_subplot(gs[0, 0])
    ax_img.imshow(img_raw)
    ax_img.set_title('① Input RGB image', fontsize=9, pad=5, color=C_TEXT)
    for sp in ax_img.spines.values():
        sp.set_edgecolor('#CCCCCC'); sp.set_linewidth(0.7)
    ax_img.tick_params(labelsize=6, colors='#BBB')
    te = BDSL47_BRAILLE[true_class]
    ax_img.set_xlabel(
        f'True sign: {te["name"]}  (class {true_class})',
        fontsize=7.5, color=C_ALPHA, labelpad=4
    )

    # ── Panel 2: hand skeleton ────────────────────────────────────────────────
    ax_hand = fig.add_subplot(gs[0, 1])
    _draw_hand_panel(ax_hand, coords_tensor)

    # ── Panel 3: model output ─────────────────────────────────────────────────
    ax_out = fig.add_subplot(gs[0, 2])
    _draw_output_panel(ax_out, pred_cls, confidence, true_class)

    # ── Panel 4: Braille ──────────────────────────────────────────────────────
    ax_br = fig.add_subplot(gs[0, 3])
    _draw_braille_panel(ax_br, pred_cls)

    # Inter-panel arrows
    for xf in [0.255, 0.490, 0.730]:
        _panel_arrow(fig, xf)

    fig.suptitle(
        f'End-to-end pipeline: BdSL sign  →  Bangladeshi Braille  [{suptitle}]\n'
        f'GVF-Net: Improved GCN + EfficientNet-B0  ·  User-independent evaluation  ·  '
        f'Braille ref: Hossain et al. 2013 + Ahmed et al. 2025  ·  All 47 patterns verified',
        fontsize=9.5, color=sc, y=0.97
    )
    plt.savefig(save_path, dpi=160, bbox_inches='tight', facecolor=C_BG)
    plt.show()
    print(f'Saved: {save_path}')

    braille_str, _ = class_to_braille(pred_cls)
    return pred_cls, braille_str, BDSL47_BRAILLE[pred_cls]


# ── Batch demo ───────────────────────────────────────────────────────────────

def batch_pipeline_demo(model, test_samples, encoder,
                        n_samples=12,
                        save_path='pipeline_batch_demo.png'):
    """
    Grid of n_samples unique classes.  Each tile: image left + Braille cell right.
    Green border = correct, red = incorrect.
    """
    random.seed(42)
    seen, selected = set(), []
    for s in random.sample(test_samples, len(test_samples)):
        cls = int(s['label'])
        if cls not in seen:
            selected.append(s); seen.add(cls)
        if len(selected) >= n_samples:
            break

    ncols    = 4
    nrows    = (len(selected) + ncols - 1) // ncols
    fig_w    = ncols * 5.8
    fig_h    = nrows * 5.4 + 1.0

    fig = plt.figure(figsize=(fig_w, fig_h), facecolor=C_BG)
    fig.patch.set_facecolor(C_BG)

    gs_outer = mgridspec.GridSpec(
        nrows, ncols,
        hspace=0.52, wspace=0.38,
        left=0.02, right=0.98,
        top=0.91,  bottom=0.02
    )

    model.eval()
    correct_count = 0

    for i, s in enumerate(selected):
        row, col = i // ncols, i % ncols
        gs_in = GridSpecFromSubplotSpec(
            2, 2,
            subplot_spec=gs_outer[row, col],
            height_ratios=[3.2, 1.0],
            width_ratios=[1.05, 0.95],
            hspace=0.06, wspace=0.18
        )
        ax_img  = fig.add_subplot(gs_in[0, 0])
        ax_cell = fig.add_subplot(gs_in[0, 1])
        ax_info = fig.add_subplot(gs_in[1, :])

        true_cls  = int(s['label'])
        img_raw   = PILImage.open(s['img_path']).convert('RGB')
        img_t     = EVAL_TF(img_raw).unsqueeze(0).to(device)
        coords_t  = torch.tensor(s['coords']).unsqueeze(0).to(device)

        with torch.no_grad():
            pred_enc = model(img_t, coords_t).argmax(1).item()
        pred_cls  = int(encoder.inverse_transform([pred_enc])[0])
        correct   = pred_cls == true_cls
        if correct: correct_count += 1

        e   = BDSL47_BRAILLE[pred_cls]
        te  = BDSL47_BRAILLE[true_cls]
        bc  = C_CORRECT if correct else C_INCORRECT
        sym = '✓' if correct else '✗'

        # Image
        ax_img.imshow(img_raw)
        ax_img.axis('off')
        for sp in ax_img.spines.values():
            sp.set_visible(True); sp.set_edgecolor(bc); sp.set_linewidth(2.8)
        ax_img.set_title(
            f'Pred: {e["name"]}  {sym}',
            fontsize=8, color=bc, pad=3, fontweight='bold'
        )

        # Braille cell
        is_digit = e['type'] == 'digit'
        dc = C_DIGIT if is_digit else C_ALPHA
        de = C_DIGIT_E if is_digit else C_ALPHA_E
        mask = e['mask']

        ax_cell.set_xlim(0, 1); ax_cell.set_ylim(0, 1)
        ax_cell.set_aspect('equal'); ax_cell.axis('off')

        tag  = 'DIGIT' if is_digit else 'ALPHA'
        lbl  = '2-cell' if is_digit else '1-cell'
        tc   = C_DIGIT if is_digit else C_ALPHA

        ax_cell.text(0.5, 0.98,
                     f'Class {pred_cls}: {e["name"]}  [{lbl}]',
                     ha='center', va='top', fontsize=6.5,
                     color=tc, fontweight='bold',
                     transform=ax_cell.transAxes)

        S = 0.78
        cw = _cell_width(S)
        if is_digit:
            _draw_bordered_cell(ax_cell, NS_MASK, C_NS, C_ALPHA_E,
                                0.02, 0.10, S)
            _draw_bordered_cell(ax_cell, mask,    dc,   de,
                                0.02 + cw + 0.04, 0.10, S)
        else:
            xo = (1.0 - cw) / 2
            _draw_bordered_cell(ax_cell, mask, dc, de, xo, 0.10, S)

        braille_str, _ = class_to_braille(pred_cls)
        active = ', '.join(str(k+1) for k in range(6) if (mask>>k)&1) or '—'
        uc_str = (f"U+283C·U+{0x2800+mask:04X}" if is_digit
                  else f"U+{0x2800+mask:04X}")

        # Info strip
        ax_info.axis('off')
        ax_info.text(0.5, 0.92,
                     f'True: {te["name"]}  (class {true_cls})',
                     ha='center', va='top', fontsize=6.5, color=C_MUTED,
                     transform=ax_info.transAxes)
        ax_info.text(0.5, 0.46,
                     f"{e['sign']}  ↳ {uc_str}   Dots: {active}",
                     ha='center', va='top', fontsize=6.0,
                     color=C_TEXT, fontfamily='monospace',
                     transform=ax_info.transAxes)

    demo_acc = 100. * correct_count / len(selected)

    legend_els = [
        mpatches.Patch(facecolor=C_CORRECT,   edgecolor=C_CORRECT,
                       label=f'Correct  ({correct_count}/{len(selected)})'),
        mpatches.Patch(facecolor=C_INCORRECT, edgecolor=C_INCORRECT,
                       label='Incorrect'),
        mpatches.Patch(facecolor=C_ALPHA,     edgecolor=C_ALPHA_E,
                       label='Alphabet dot'),
        mpatches.Patch(facecolor=C_DIGIT,     edgecolor=C_DIGIT_E,
                       label='Digit dot'),
    ]
    fig.legend(handles=legend_els, loc='upper right',
               fontsize=7.5, framealpha=0.95,
               bbox_to_anchor=(0.99, 0.995))

    fig.suptitle(
        f'Batch pipeline demo: BdSL sign  →  Bangladeshi Braille  ·  GVF-Net\n'
        f'Demo accuracy: {demo_acc:.0f}%  ·  '
        f'Green border = correct   ·   Red border = incorrect  ·  '
        f'Left: input image   ·   Right: predicted Braille cell\n'
        f'Ref: Hossain et al. 2013 + Ahmed et al. 2025  ·  All 47 patterns verified',
        fontsize=9.5, color=C_TEXT, y=0.995
    )
    plt.savefig(save_path, dpi=150, bbox_inches='tight', facecolor=C_BG)
    plt.show()
    print(f'Saved: {save_path}')


# ── Run ───────────────────────────────────────────────────────────────────────
s = test_samples[0]
run_pipeline(
    model=fusion_model,
    image_path=s['img_path'],
    coords_tensor=torch.tensor(s['coords'], dtype=torch.float32),
    encoder=encoder,
    true_class=int(s['label']),
    save_path='pipeline_single_demo.png'
)

batch_pipeline_demo(
    model=fusion_model,
    test_samples=test_samples,
    encoder=encoder,
    n_samples=12,
    save_path='pipeline_batch_demo.png'
)

